import { Worker, Job, type WorkerOptions } from 'bullmq';
import { Stagehand } from '@browserbasehq/stagehand';
import { generateText } from 'ai';
import { openai } from '@ai-sdk/openai';
import { sharedRedisConnection } from '../../utils/redis.js';
import { logger } from '../../utils/logger.js';
import { getDrizzle } from '../../db/connection.js';
import { posts } from '../../db/schema.js';
import crypto from 'node:crypto';

interface ScraperJobData {
  automationId: string;
  flowData: {
    nodes: any[];
    edges: any[];
  };
  userId: string;
  workspaceId: string;
}

export const scraperWorker = new Worker<ScraperJobData>(
  'scraper-flow',
  async (job: Job<ScraperJobData>) => {
    const { automationId, flowData, userId, workspaceId } = job.data;
    logger.info(`Starting execution for automation flow: ${automationId}`);

    const { nodes, edges } = flowData;

    // Simple execution: find URL trigger, then scrape action, then AI, then Post
    // In a real robust system, we would do a proper topological sort.
    const urlTrigger = nodes.find((n) => n.data?.type === 'trigger' && n.id.includes('url'));
    const scrapeAction = nodes.find((n) => n.data?.type === 'action' && n.id.includes('scrape'));
    const aiAction = nodes.find((n) => n.data?.type === 'action' && n.id.includes('ai'));
    const postAction = nodes.find((n) => n.data?.type === 'action' && n.id.includes('post'));

    let extractedData = '';

    if (urlTrigger && scrapeAction) {
      const urlToScrape = urlTrigger.data.url || 'https://news.ycombinator.com';
      const scrapeInstruction = scrapeAction.data.instruction || 'Extract the top 3 news articles and their URLs';
      
      logger.info(`Stagehand: Navigating to ${urlToScrape}`);
      
      // Initialize Stagehand (Local execution)
      const stagehand = new Stagehand({
        env: 'LOCAL',
        verbose: 1,
        logger: (msg) => logger.debug(`[Stagehand] ${msg.message}`)
      });

      try {
        await stagehand.init();
        const page = (stagehand as any).page;
        await page.goto(urlToScrape);
        
        logger.info(`Stagehand: Extracting with instruction: "${scrapeInstruction}"`);
        const extraction = await page.extract(scrapeInstruction);
        extractedData = JSON.stringify(extraction, null, 2);
        
        logger.info('Stagehand: Extraction successful.');
      } catch (e: any) {
        logger.error(`Stagehand error: ${e.message}`);
        throw e;
      } finally {
        await stagehand.close();
      }
    }

    let finalContent = extractedData;

    if (aiAction && extractedData) {
      const prompt = aiAction.data.prompt || 'Summarize this data into a LinkedIn post';
      logger.info('AI: Processing extracted data');
      
      const response = await generateText({
        model: openai('gpt-4o-mini'),
        messages: [
          { role: 'system', content: 'You are a social media expert.' },
          { role: 'user', content: `${prompt}\n\nData:\n${extractedData}` }
        ]
      });
      
      finalContent = response.text;
    }

    if (postAction && finalContent) {
      logger.info('Action: Saving to drafts');
      const db = getDrizzle();
      await db.insert(posts).values({
        id: crypto.randomUUID(),
        userId,
        workspaceId,
        content: finalContent,
        status: 'draft',
        platforms: JSON.stringify(['linkedin']),
        originalPrompt: 'Generated by Automation Flow',
        llmProvider: 'openai',
      });
      logger.info(`Draft created successfully for automation ${automationId}`);
    }

    return { success: true, finalContent };
  },
  {
    connection: sharedRedisConnection as WorkerOptions['connection'],
  }
);

scraperWorker.on('completed', (job) => {
  logger.info(`Scraper Job ${job.id} has completed successfully`);
});

scraperWorker.on('failed', (job, err) => {
  logger.error(`Scraper Job ${job?.id} has failed: ${err.message}`);
});
