export const PLATFORMS = {
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    charLimit: 3000,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 10,
    color: '#0A66C2',
    icon: 'linkedin',
  },
  twitter: {
    id: 'twitter',
    name: 'X / Twitter',
    charLimit: 280,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 5,
    color: '#000000',
    icon: 'twitter',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    charLimit: 63206,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 10,
    color: '#1877F2',
    icon: 'facebook',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    charLimit: 2200,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 30,
    color: '#E4405F',
    icon: 'instagram',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    charLimit: 2200,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 10,
    color: '#000000',
    icon: 'music',
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    charLimit: 500,
    supportsMedia: true,
    supportsHashtags: true,
    maxHashtags: 20,
    color: '#BD081C',
    icon: 'pin',
  },
} as const;

export type PlatformId = keyof typeof PLATFORMS;
export type Platform = (typeof PLATFORMS)[PlatformId];
