import { useTranslation } from 'react-i18next';
import { FileText, ArrowUp } from 'lucide-react';
import { useEffect, useState, useRef, useCallback } from 'react';
import clsx from 'clsx';

/* ------------------------------------------------------------------ */
/*  Terms of Service Data                                               */
/* ------------------------------------------------------------------ */
function useTermsSections() {
  const { t } = useTranslation();

  return [
    {
      id: 'acceptance',
      title: t('marketing.terms.s1Title', '1. Acceptance of Terms'),
      content: t(
        'marketing.terms.s1Content',
        'By accessing or using PostCommander (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you ("User", "you") and PostCommander SAS ("Company", "we", "us").\n\nBy creating an account, you represent that you are at least 18 years of age, or the age of majority in your jurisdiction, whichever is greater. If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.',
      ),
    },
    {
      id: 'service-description',
      title: t('marketing.terms.s2Title', '2. Service Description'),
      content: t(
        'marketing.terms.s2Content',
        'PostCommander is an AI-powered social media content creation platform that enables users to generate, optimize, and manage content across multiple social media platforms including LinkedIn, X (Twitter), Facebook, Instagram, TikTok, and Pinterest.\n\nThe Service utilizes multiple third-party artificial intelligence models including OpenAI GPT, Anthropic Claude, Google Gemini, Mistral AI, and optional local models via Ollama to generate content based on user inputs. The Service includes features such as content generation, style cloning, carousel creation, content repurposing, hashtag research, A/B testing, engagement prediction, and content scheduling.',
      ),
    },
    {
      id: 'user-accounts',
      title: t('marketing.terms.s3Title', '3. User Accounts'),
      content: t(
        'marketing.terms.s3Content',
        'To access certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information up to date.\n\nYou are responsible for safeguarding the password associated with your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized access to or use of your account. We reserve the right to disable any account at any time if we believe you have violated any provision of these Terms.',
      ),
    },
    {
      id: 'subscription-payment',
      title: t('marketing.terms.s4Title', '4. Subscription & Payment'),
      content: t(
        'marketing.terms.s4Content',
        'PostCommander offers free and paid subscription plans. Paid subscriptions are billed monthly or annually through Stripe unless a separate written agreement says otherwise. Taxes may apply depending on your location.\n\nBy subscribing to a paid plan, you authorize recurring charges until you cancel. You may cancel a subscription from the billing area of the product, and paid access continues until the end of the current billing period unless a different term is stated in a custom agreement.\n\nWe may update pricing or packaging over time. Changes apply prospectively, and continued use after the effective date means you accept the updated pricing.',
      ),
    },
    {
      id: 'content-ip',
      title: t('marketing.terms.s5Title', '5. Content & Intellectual Property'),
      content: t(
        'marketing.terms.s5Content',
        'You retain all rights to the content you create, upload, or generate through the Service ("User Content"). By using the Service, you grant us a limited license to process your content solely for the purpose of providing and improving the Service.\n\nThe PostCommander platform, including its design, features, code, and documentation, is protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the Service without our express written permission.\n\nYou acknowledge that the Service generates content using AI models and that similar or identical content may be generated for other users based on similar inputs. You are solely responsible for reviewing, editing, and ensuring the appropriateness of all content before publishing.',
      ),
    },
    {
      id: 'ai-disclaimer',
      title: t('marketing.terms.s6Title', '6. AI-Generated Content Disclaimer'),
      content: t(
        'marketing.terms.s6Content',
        'Content generated by the Service is produced by artificial intelligence models and may contain inaccuracies, errors, or inappropriate material. We do not guarantee the accuracy, completeness, or suitability of AI-generated content for any particular purpose.\n\nYou are solely responsible for reviewing, verifying, and editing all AI-generated content before use or publication. You agree not to hold PostCommander liable for any damages arising from the use of AI-generated content, including but not limited to defamation, copyright infringement, or regulatory violations.\n\nAI-generated content should not be used as a substitute for professional advice, including but not limited to legal, medical, financial, or other expert counsel.',
      ),
    },
    {
      id: 'acceptable-use',
      title: t('marketing.terms.s7Title', '7. Acceptable Use'),
      content: t(
        'marketing.terms.s7Content',
        'You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:\n\n- Use the Service to generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable\n- Attempt to circumvent usage limits, rate limits, or other technical restrictions\n- Use the Service to generate spam, misleading content, or content designed to deceive\n- Impersonate any person or entity or misrepresent your affiliation with any person or entity\n- Use the Service to generate content that infringes on the intellectual property rights of others\n- Attempt to reverse-engineer, decompile, or extract the underlying AI models, algorithms, or training data\n- Use the Service in any way that could damage, disable, overburden, or impair the Service',
      ),
    },
    {
      id: 'platform-integration',
      title: t('marketing.terms.s8Title', '8. Platform Integration'),
      content: t(
        'marketing.terms.s8Content',
        'The Service integrates with third-party social media platforms and AI providers. Your use of these third-party services is subject to their respective terms of service and privacy policies.\n\nWe do not control and are not responsible for the content, privacy policies, or practices of any third-party platform. You acknowledge that your use of third-party APIs and services is at your own risk.\n\nWe reserve the right to add, modify, or remove integrations with third-party platforms at any time without prior notice. We are not responsible for any disruption of service caused by changes to third-party APIs or services.',
      ),
    },
    {
      id: 'data-privacy',
      title: t('marketing.terms.s9Title', '9. Data Privacy'),
      content: t(
        'marketing.terms.s9Content',
        'Your privacy is important to us. Our collection and use of personal data is governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of your data as described in our Privacy Policy.\n\nPlease review our Privacy Policy at /privacy to understand our data practices.',
      ),
    },
    {
      id: 'limitation-liability',
      title: t('marketing.terms.s10Title', '10. Limitation of Liability'),
      content: t(
        'marketing.terms.s10Content',
        'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, POSTCOMMANDER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM:\n\n(A) YOUR USE OF OR INABILITY TO USE THE SERVICE;\n(B) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY PERSONAL INFORMATION STORED THEREIN;\n(C) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE;\n(D) ANY CONTENT GENERATED BY THE AI MODELS;\n(E) ANY BUGS, VIRUSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE SERVICE.\n\nIN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE GREATER OF ONE HUNDRED EUROS (100 EUR) OR THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.',
      ),
    },
    {
      id: 'termination',
      title: t('marketing.terms.s11Title', '11. Termination'),
      content: t(
        'marketing.terms.s11Content',
        'We may suspend or terminate access to the Service if you breach these Terms, create material security risk, or abuse the platform.\n\nYou may also terminate your account yourself from Settings through the account deletion flow. When an account is deleted, active application data is removed from the product database. Limited archived billing or deletion audit records may still be retained for support, accounting, fraud prevention, or legal obligations, and third-party processors such as Stripe may retain their own records according to their policies.\n\nProvisions that should survive termination, including ownership, payment obligations already incurred, warranty disclaimers, and limitations of liability, remain in effect.',
      ),
    },
    {
      id: 'changes',
      title: t('marketing.terms.s12Title', '12. Changes to Terms'),
      content: t(
        'marketing.terms.s12Content',
        'We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on the Service and updating the "Last Updated" date.\n\nYour continued use of the Service after any changes to the Terms constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Service and close your account.',
      ),
    },
    {
      id: 'contact',
      title: t('marketing.terms.s13Title', '13. Contact'),
      content: t(
        'marketing.terms.s13Content',
        'If you have any questions about these Terms of Service, please contact us:\n\nPostCommander SAS\nEmail: legal@postcommander.com\nAddress: Paris, France\n\nFor general inquiries, please visit our Contact page at /contact.',
      ),
    },
  ];
}

/* ------------------------------------------------------------------ */
/*  Terms Page                                                          */
/* ------------------------------------------------------------------ */
export function TermsPage() {
  const { t } = useTranslation();
  const sections = useTermsSections();
  const [activeSection, setActiveSection] = useState('acceptance');
  const sectionRefs = useRef<Record<string, HTMLElement | null>>({});

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleScroll = useCallback(() => {
    const scrollY = window.scrollY + 200;
    let current = sections[0].id;
    for (const section of sections) {
      const el = sectionRefs.current[section.id];
      if (el && el.offsetTop <= scrollY) {
        current = section.id;
      }
    }
    setActiveSection(current);
  }, [sections]);

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [handleScroll]);

  const scrollToSection = (id: string) => {
    const el = sectionRefs.current[id];
    if (el) {
      window.scrollTo({ top: el.offsetTop - 100, behavior: 'smooth' });
    }
  };

  return (
    <>
      {/* Hero */}
      <section className="relative pt-28 pb-12 overflow-hidden">
        <div className="absolute inset-0 bg-[var(--color-void)]" />
        <div className="absolute inset-0 mesh-gradient opacity-50" />
        <div className="absolute inset-0 grid-pattern" />

        <div className="orb w-56 h-56 top-[20%] right-[10%] bg-[var(--color-accent-blue)]/15" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass animate-fade-in-up mb-8">
            <FileText size={14} className="text-[var(--color-accent-blue)]" />
            <span className="text-xs font-semibold text-[var(--color-text-secondary)] tracking-wide uppercase">
              {t('marketing.terms.heroBadge', 'Legal')}
            </span>
          </div>

          <h1 className="heading-lg mb-4 animate-fade-in-up" style={{ animationDelay: '0.1s' }}>
            <span className="text-white">{t('marketing.terms.heroTitle', 'Terms of Service')}</span>
          </h1>

          <p
            className="text-sm text-[var(--color-text-muted)] animate-fade-in-up"
            style={{ animationDelay: '0.2s' }}
          >
            {t('marketing.terms.lastUpdated', 'Last updated: April 16, 2026')}
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="relative py-12 overflow-hidden">
        <div className="absolute inset-0 dot-pattern" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-4 gap-12">
            {/* Sidebar TOC */}
            <aside className="hidden lg:block">
              <div className="sticky top-28">
                <h3 className="text-xs font-semibold text-[var(--color-text-muted)] uppercase tracking-wider mb-4">
                  {t('marketing.terms.tocTitle', 'Table of Contents')}
                </h3>
                <nav className="space-y-1">
                  {sections.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={clsx(
                        'block w-full text-left px-3 py-2 rounded-lg text-xs transition-all duration-200',
                        activeSection === section.id
                          ? 'text-white bg-white/[0.06] font-medium'
                          : 'text-[var(--color-text-muted)] hover:text-[var(--color-text-secondary)] hover:bg-white/[0.02]',
                      )}
                    >
                      {section.title}
                    </button>
                  ))}
                </nav>
              </div>
            </aside>

            {/* Main content */}
            <div className="lg:col-span-3 space-y-8">
              {sections.map((section, i) => (
                <div
                  key={section.id}
                  ref={(el) => {
                    sectionRefs.current[section.id] = el;
                  }}
                  className="glass-card p-6 sm:p-8 rounded-2xl animate-fade-in-up"
                  style={{ animationDelay: `${0.05 + i * 0.03}s` }}
                >
                  <h2 className="heading-sm text-white mb-4">{section.title}</h2>
                  <div className="text-sm text-[var(--color-text-secondary)] leading-relaxed whitespace-pre-line">
                    {section.content}
                  </div>
                </div>
              ))}

              {/* Back to top */}
              <div className="text-center pt-4">
                <button
                  onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-xl glass text-sm text-[var(--color-text-secondary)] hover:text-white transition-colors"
                >
                  <ArrowUp size={14} />
                  {t('marketing.terms.backToTop', 'Back to top')}
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
